#!/usr/bin/env bash
set +x
if [ ! -S ~/.ssh/ssh_auth_sock ]; then
  	eval "$(ssh-agent -s)"
    ln -sf "$SSH_AUTH_SOCK" ~/.ssh/ssh_auth_sock
fi
export SSH_AUTH_SOCK=~/.ssh/ssh_auth_sock
ssh-add -l > /dev/null || ssh-add /mnt/hgfs/linux/ssh/ganesan
ssh-add -l

